INSERT INTO public.exercise_list (name) VALUES ('Back Extension');
INSERT INTO public.exercise_list (name) VALUES ('Cable Bicep Curl');
INSERT INTO public.exercise_list (name) VALUES ('Calf Press');
INSERT INTO public.exercise_list (name) VALUES ('Glute Kickback');
INSERT INTO public.exercise_list (name) VALUES ('Iso-lateral Row');
INSERT INTO public.exercise_list (name) VALUES ('Bench Press (Barbell)');
INSERT INTO public.exercise_list (name) VALUES ('Lat Pulldown - Close Grip (Cable)');
INSERT INTO public.exercise_list (name) VALUES ('Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise_list (name) VALUES ('Incline Bench Press (Smith Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Iso-Lateral Row (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Seated Row (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Pullover (Dumbbell)');
INSERT INTO public.exercise_list (name) VALUES ('Bicep Curl (Dumbbell)');
INSERT INTO public.exercise_list (name) VALUES ('Bayesian Cable Curl');
INSERT INTO public.exercise_list (name) VALUES ('Hammer Curl (Dumbbell)');
INSERT INTO public.exercise_list (name) VALUES ('Triceps Pushdown');
INSERT INTO public.exercise_list (name) VALUES ('Triceps Extension (Cable)');
INSERT INTO public.exercise_list (name) VALUES ('Rear Delt Reverse Fly (Cable)');
INSERT INTO public.exercise_list (name) VALUES ('Lateral Raise (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Lat Pulldown (Cable)');
INSERT INTO public.exercise_list (name) VALUES ('Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Butterfly (Pec Deck)');
INSERT INTO public.exercise_list (name) VALUES ('Iso-Lateral Chest Press (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Reverse Curl (Cable)');
INSERT INTO public.exercise_list (name) VALUES ('Seated Cable Row - Bar Wide Grip');
INSERT INTO public.exercise_list (name) VALUES ('Hack Squat (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Romanian Deadlift (Barbell)');
INSERT INTO public.exercise_list (name) VALUES ('Seated Leg Curl (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Supine Press');
INSERT INTO public.exercise_list (name) VALUES ('Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise_list (name) VALUES ('Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise_list (name) VALUES ('Bulgarian Split Squat');
INSERT INTO public.exercise_list (name) VALUES ('Leg Raise Parallel Bars');
INSERT INTO public.exercise_list (name) VALUES ('Preacher Curl (Hammer)');
INSERT INTO public.exercise_list (name) VALUES ('Squat (Barbell)');
INSERT INTO public.exercise_list (name) VALUES ('Cable Fly Crossovers');
INSERT INTO public.exercise_list (name) VALUES ('Lateral Raise (Dumbbell)');
INSERT INTO public.exercise_list (name) VALUES ('Chest Supported Incline Row (Dumbbell)');
INSERT INTO public.exercise_list (name) VALUES ('Dumbbell Row');
INSERT INTO public.exercise_list (name) VALUES ('Leg Extension (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('EZ Bar Biceps Curl');
INSERT INTO public.exercise_list (name) VALUES ('Hammer Curl Bar');
INSERT INTO public.exercise_list (name) VALUES ('Pull Up');
INSERT INTO public.exercise_list (name) VALUES ('Pull Up (Weighted)');
INSERT INTO public.exercise_list (name) VALUES ('T Bar Row');
INSERT INTO public.exercise_list (name) VALUES ('Bent Over Row (Barbell)');
INSERT INTO public.exercise_list (name) VALUES ('Overhead Press (Barbell)');
INSERT INTO public.exercise_list (name) VALUES ('Preacher Curl (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Meadows Rows (Barbell)');
INSERT INTO public.exercise_list (name) VALUES ('Seated Dip Machine');
INSERT INTO public.exercise_list (name) VALUES ('Seated Calf Raise');
INSERT INTO public.exercise_list (name) VALUES ('Lying Leg Curl (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Chest Fly (Dumbbell)');
INSERT INTO public.exercise_list (name) VALUES ('Deadlift (Barbell)');
INSERT INTO public.exercise_list (name) VALUES ('Preacher Curl (Barbell)');
INSERT INTO public.exercise_list (name) VALUES ('Iso Lateral Low Row');
INSERT INTO public.exercise_list (name) VALUES ('Seated Cable Row - V Grip (Cable)');
INSERT INTO public.exercise_list (name) VALUES ('Unilateral Rear Delts (Nipples)');
INSERT INTO public.exercise_list (name) VALUES ('Hip Abduction (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Hip Adduction (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Crunch (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Pull Up (Assisted)');
INSERT INTO public.exercise_list (name) VALUES ('Triceps Kickback (Cable)');
INSERT INTO public.exercise_list (name) VALUES ('Shrug (Barbell)');
INSERT INTO public.exercise_list (name) VALUES ('Shoulder Press (Dumbbell)');
INSERT INTO public.exercise_list (name) VALUES ('Chest Press (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Bicep Curl (Cable)');
INSERT INTO public.exercise_list (name) VALUES ('Iso-Lateral Low Row');
INSERT INTO public.exercise_list (name) VALUES ('Triceps Dip');
INSERT INTO public.exercise_list (name) VALUES ('Low Cable Fly Crossovers');
INSERT INTO public.exercise_list (name) VALUES ('Bench Press (Smith Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Squat (Smith Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Deadlift (Smith Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Leg Press Horizontal (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Standing Calf Raise (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Leg Press (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Hip Thrust (Barbell)');
INSERT INTO public.exercise_list (name) VALUES ('Bench Dip');
INSERT INTO public.exercise_list (name) VALUES ('Iso-Lateral High Row (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Seated Chest Flys (Cable)');
INSERT INTO public.exercise_list (name) VALUES ('Shrug (Dumbbell)');
INSERT INTO public.exercise_list (name) VALUES ('Back Extension (Weighted Hyperextension)');
INSERT INTO public.exercise_list (name) VALUES ('Shrug (Cable)');
INSERT INTO public.exercise_list (name) VALUES ('Squat (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Cross Arm Lat Pull Around');
INSERT INTO public.exercise_list (name) VALUES ('Calf Extension (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Straight Arm Lat Pulldown (Cable)');
INSERT INTO public.exercise_list (name) VALUES ('Decline Crunch');
INSERT INTO public.exercise_list (name) VALUES ('Single Arm Lat Pulldown');
INSERT INTO public.exercise_list (name) VALUES ('Bench Press (Dumbbell)');
INSERT INTO public.exercise_list (name) VALUES ('Spider Curl (Barbell)');
INSERT INTO public.exercise_list (name) VALUES ('Single Arm Triceps Pushdown (Cable)');
INSERT INTO public.exercise_list (name) VALUES ('Triceps Rope Pushdown');
INSERT INTO public.exercise_list (name) VALUES ('Seated Palms Up Wrist Curl');
INSERT INTO public.exercise_list (name) VALUES ('Skullcrusher (Barbell)');
INSERT INTO public.exercise_list (name) VALUES ('Incline Bench Press (Barbell)');
INSERT INTO public.exercise_list (name) VALUES ('Triceps Extension (Machine)');
INSERT INTO public.exercise_list (name) VALUES ('Hammer Curl (Cable)');
