INSERT INTO public.exercise_list (name, id) VALUES ('Back Extension', 1);
INSERT INTO public.exercise_list (name, id) VALUES ('Cable Bicep Curl', 2);
INSERT INTO public.exercise_list (name, id) VALUES ('Calf Press', 3);
INSERT INTO public.exercise_list (name, id) VALUES ('Glute Kickback', 4);
INSERT INTO public.exercise_list (name, id) VALUES ('Iso-lateral Row', 5);
INSERT INTO public.exercise_list (name, id) VALUES ('Bench Press (Barbell)', 6);
INSERT INTO public.exercise_list (name, id) VALUES ('Lat Pulldown - Close Grip (Cable)', 7);
INSERT INTO public.exercise_list (name, id) VALUES ('Incline Bench Press (Dumbbell)', 8);
INSERT INTO public.exercise_list (name, id) VALUES ('Incline Bench Press (Smith Machine)', 9);
INSERT INTO public.exercise_list (name, id) VALUES ('Iso-Lateral Row (Machine)', 10);
INSERT INTO public.exercise_list (name, id) VALUES ('Seated Row (Machine)', 11);
INSERT INTO public.exercise_list (name, id) VALUES ('Pullover (Dumbbell)', 12);
INSERT INTO public.exercise_list (name, id) VALUES ('Bicep Curl (Dumbbell)', 13);
INSERT INTO public.exercise_list (name, id) VALUES ('Bayesian Cable Curl', 14);
INSERT INTO public.exercise_list (name, id) VALUES ('Hammer Curl (Dumbbell)', 15);
INSERT INTO public.exercise_list (name, id) VALUES ('Triceps Pushdown', 16);
INSERT INTO public.exercise_list (name, id) VALUES ('Triceps Extension (Cable)', 17);
INSERT INTO public.exercise_list (name, id) VALUES ('Rear Delt Reverse Fly (Cable)', 18);
INSERT INTO public.exercise_list (name, id) VALUES ('Lateral Raise (Machine)', 19);
INSERT INTO public.exercise_list (name, id) VALUES ('Lat Pulldown (Cable)', 20);
INSERT INTO public.exercise_list (name, id) VALUES ('Rear Delt Reverse Fly (Machine)', 21);
INSERT INTO public.exercise_list (name, id) VALUES ('Butterfly (Pec Deck)', 22);
INSERT INTO public.exercise_list (name, id) VALUES ('Iso-Lateral Chest Press (Machine)', 23);
INSERT INTO public.exercise_list (name, id) VALUES ('Reverse Curl (Cable)', 24);
INSERT INTO public.exercise_list (name, id) VALUES ('Seated Cable Row - Bar Wide Grip', 25);
INSERT INTO public.exercise_list (name, id) VALUES ('Hack Squat (Machine)', 26);
INSERT INTO public.exercise_list (name, id) VALUES ('Romanian Deadlift (Barbell)', 27);
INSERT INTO public.exercise_list (name, id) VALUES ('Seated Leg Curl (Machine)', 28);
INSERT INTO public.exercise_list (name, id) VALUES ('Supine Press', 29);
INSERT INTO public.exercise_list (name, id) VALUES ('Seated Incline Curl (Dumbbell)', 30);
INSERT INTO public.exercise_list (name, id) VALUES ('Single Arm Lateral Raise (Cable)', 31);
INSERT INTO public.exercise_list (name, id) VALUES ('Bulgarian Split Squat', 32);
INSERT INTO public.exercise_list (name, id) VALUES ('Leg Raise Parallel Bars', 33);
INSERT INTO public.exercise_list (name, id) VALUES ('Preacher Curl (Hammer)', 34);
INSERT INTO public.exercise_list (name, id) VALUES ('Squat (Barbell)', 35);
INSERT INTO public.exercise_list (name, id) VALUES ('Cable Fly Crossovers', 36);
INSERT INTO public.exercise_list (name, id) VALUES ('Lateral Raise (Dumbbell)', 37);
INSERT INTO public.exercise_list (name, id) VALUES ('Chest Supported Incline Row (Dumbbell)', 38);
INSERT INTO public.exercise_list (name, id) VALUES ('Dumbbell Row', 39);
INSERT INTO public.exercise_list (name, id) VALUES ('Leg Extension (Machine)', 40);
INSERT INTO public.exercise_list (name, id) VALUES ('EZ Bar Biceps Curl', 41);
INSERT INTO public.exercise_list (name, id) VALUES ('Hammer Curl Bar', 42);
INSERT INTO public.exercise_list (name, id) VALUES ('Pull Up', 43);
INSERT INTO public.exercise_list (name, id) VALUES ('Pull Up (Weighted)', 44);
INSERT INTO public.exercise_list (name, id) VALUES ('T Bar Row', 45);
INSERT INTO public.exercise_list (name, id) VALUES ('Bent Over Row (Barbell)', 46);
INSERT INTO public.exercise_list (name, id) VALUES ('Overhead Press (Barbell)', 47);
INSERT INTO public.exercise_list (name, id) VALUES ('Preacher Curl (Machine)', 48);
INSERT INTO public.exercise_list (name, id) VALUES ('Meadows Rows (Barbell)', 49);
INSERT INTO public.exercise_list (name, id) VALUES ('Seated Dip Machine', 50);
INSERT INTO public.exercise_list (name, id) VALUES ('Seated Calf Raise', 51);
INSERT INTO public.exercise_list (name, id) VALUES ('Lying Leg Curl (Machine)', 52);
INSERT INTO public.exercise_list (name, id) VALUES ('Chest Fly (Dumbbell)', 53);
INSERT INTO public.exercise_list (name, id) VALUES ('Deadlift (Barbell)', 54);
INSERT INTO public.exercise_list (name, id) VALUES ('Preacher Curl (Barbell)', 55);
INSERT INTO public.exercise_list (name, id) VALUES ('Iso Lateral Low Row', 56);
INSERT INTO public.exercise_list (name, id) VALUES ('Seated Cable Row - V Grip (Cable)', 57);
INSERT INTO public.exercise_list (name, id) VALUES ('Unilateral Rear Delts (Nipples)', 58);
INSERT INTO public.exercise_list (name, id) VALUES ('Hip Abduction (Machine)', 59);
INSERT INTO public.exercise_list (name, id) VALUES ('Hip Adduction (Machine)', 60);
INSERT INTO public.exercise_list (name, id) VALUES ('Crunch (Machine)', 61);
INSERT INTO public.exercise_list (name, id) VALUES ('Pull Up (Assisted)', 62);
INSERT INTO public.exercise_list (name, id) VALUES ('Triceps Kickback (Cable)', 63);
INSERT INTO public.exercise_list (name, id) VALUES ('Shrug (Barbell)', 64);
INSERT INTO public.exercise_list (name, id) VALUES ('Shoulder Press (Dumbbell)', 65);
INSERT INTO public.exercise_list (name, id) VALUES ('Chest Press (Machine)', 66);
INSERT INTO public.exercise_list (name, id) VALUES ('Bicep Curl (Cable)', 67);
INSERT INTO public.exercise_list (name, id) VALUES ('Iso-Lateral Low Row', 68);
INSERT INTO public.exercise_list (name, id) VALUES ('Triceps Dip', 69);
INSERT INTO public.exercise_list (name, id) VALUES ('Low Cable Fly Crossovers', 70);
INSERT INTO public.exercise_list (name, id) VALUES ('Bench Press (Smith Machine)', 71);
INSERT INTO public.exercise_list (name, id) VALUES ('Squat (Smith Machine)', 72);
INSERT INTO public.exercise_list (name, id) VALUES ('Deadlift (Smith Machine)', 73);
INSERT INTO public.exercise_list (name, id) VALUES ('Leg Press Horizontal (Machine)', 74);
INSERT INTO public.exercise_list (name, id) VALUES ('Standing Calf Raise (Machine)', 75);
INSERT INTO public.exercise_list (name, id) VALUES ('Leg Press (Machine)', 76);
INSERT INTO public.exercise_list (name, id) VALUES ('Hip Thrust (Barbell)', 77);
INSERT INTO public.exercise_list (name, id) VALUES ('Bench Dip', 78);
INSERT INTO public.exercise_list (name, id) VALUES ('Iso-Lateral High Row (Machine)', 79);
INSERT INTO public.exercise_list (name, id) VALUES ('Seated Chest Flys (Cable)', 80);
INSERT INTO public.exercise_list (name, id) VALUES ('Shrug (Dumbbell)', 81);
INSERT INTO public.exercise_list (name, id) VALUES ('Back Extension (Weighted Hyperextension)', 82);
INSERT INTO public.exercise_list (name, id) VALUES ('Shrug (Cable)', 83);
INSERT INTO public.exercise_list (name, id) VALUES ('Squat (Machine)', 84);
INSERT INTO public.exercise_list (name, id) VALUES ('Cross Arm Lat Pull Around', 85);
INSERT INTO public.exercise_list (name, id) VALUES ('Calf Extension (Machine)', 86);
INSERT INTO public.exercise_list (name, id) VALUES ('Straight Arm Lat Pulldown (Cable)', 87);
INSERT INTO public.exercise_list (name, id) VALUES ('Decline Crunch', 88);
INSERT INTO public.exercise_list (name, id) VALUES ('Single Arm Lat Pulldown', 89);
INSERT INTO public.exercise_list (name, id) VALUES ('Bench Press (Dumbbell)', 90);
INSERT INTO public.exercise_list (name, id) VALUES ('Spider Curl (Barbell)', 91);
INSERT INTO public.exercise_list (name, id) VALUES ('Single Arm Triceps Pushdown (Cable)', 92);
INSERT INTO public.exercise_list (name, id) VALUES ('Triceps Rope Pushdown', 93);
INSERT INTO public.exercise_list (name, id) VALUES ('Seated Palms Up Wrist Curl', 94);
INSERT INTO public.exercise_list (name, id) VALUES ('Skullcrusher (Barbell)', 95);
INSERT INTO public.exercise_list (name, id) VALUES ('Incline Bench Press (Barbell)', 96);
INSERT INTO public.exercise_list (name, id) VALUES ('Triceps Extension (Machine)', 97);
INSERT INTO public.exercise_list (name, id) VALUES ('Hammer Curl (Cable)', 98);
INSERT INTO public.exercise_list (name, id) VALUES ('Single Arm Cable Row', 99);
INSERT INTO public.exercise_list (name, id) VALUES ('Bicep Curl (Barbell)', 100);
INSERT INTO public.exercise_list (name, id) VALUES ('Reverse Grip Smith machine Flat Bench Press', 101);
INSERT INTO public.exercise_list (name, id) VALUES ('Chest Fly (Machine)', 102);
INSERT INTO public.exercise_list (name, id) VALUES ('Iso-Lateral Machine Row', 103);
INSERT INTO public.exercise_list (name, id) VALUES ('Seated Cable Row - Bar Grip', 104);
INSERT INTO public.exercise_list (name, id) VALUES ('Lying Chest Press', 105);
INSERT INTO public.exercise_list (name, id) VALUES ('Back Extension (Machine)', 106);
INSERT INTO public.exercise_list (name, id) VALUES ('Incline Chest Press (Machine)', 107);
INSERT INTO public.exercise_list (name, id) VALUES ('Chin Up (Weighted)', 108);
INSERT INTO public.exercise_list (name, id) VALUES ('Triceps Dip (Weighted)', 109);
INSERT INTO public.exercise_list (name, id) VALUES ('Decline Push Up', 110);
INSERT INTO public.exercise_list (name, id) VALUES ('Diamond Push Up', 111);
INSERT INTO public.exercise_list (name, id) VALUES ('Handstand Hold', 112);
INSERT INTO public.exercise_list (name, id) VALUES ('Ring Dips', 113);
INSERT INTO public.exercise_list (name, id) VALUES ('Incline Push Ups', 114);
INSERT INTO public.exercise_list (name, id) VALUES ('Drinks', 115);
INSERT INTO public.exercise_list (name, id) VALUES ('Pullover (Machine)', 116);
INSERT INTO public.exercise_list (name, id) VALUES ('Belt Squat', 117);
INSERT INTO public.exercise_list (name, id) VALUES ('Bicep Curl (Machine)', 118);
INSERT INTO public.exercise_list (name, id) VALUES ('Nordic Hamstrings Curls', 119);
INSERT INTO public.exercise_list (name, id) VALUES ('Reverse Curl (Barbell)', 120);
INSERT INTO public.exercise_list (name, id) VALUES ('Upright Row (Barbell)', 121);
INSERT INTO public.exercise_list (name, id) VALUES ('Standing Leg Curls', 122);
INSERT INTO public.exercise_list (name, id) VALUES ('Rear Delt Reverse Fly (Dumbbell)', 123);
INSERT INTO public.exercise_list (name, id) VALUES ('Preacher Curl (Dumbbell)', 124);
INSERT INTO public.exercise_list (name, id) VALUES ('Dead Hang', 125);
INSERT INTO public.exercise_list (name, id) VALUES ('Farmers Walk', 126);
INSERT INTO public.exercise_list (name, id) VALUES ('Seated Shoulder Press (Machine)', 127);
INSERT INTO public.exercise_list (name, id) VALUES ('Concentration Curl', 128);
INSERT INTO public.exercise_list (name, id) VALUES ('Shrug (Smith Machine)', 129);
INSERT INTO public.exercise_list (name, id) VALUES ('Cable Crunch', 130);
INSERT INTO public.exercise_list (name, id) VALUES ('Seated Wrist Extension (Barbell)', 131);
INSERT INTO public.exercise_list (name, id) VALUES ('Calf Press (Machine)', 132);
INSERT INTO public.exercise_list (name, id) VALUES ('Hanging Leg Raise', 133);
INSERT INTO public.exercise_list (name, id) VALUES ('Lateral Raise (Cable)', 134);
INSERT INTO public.exercise_list (name, id) VALUES ('Lying Neck Curls (Weighted)', 135);
INSERT INTO public.exercise_list (name, id) VALUES ('Lying Neck Extension (Weighted)', 136);
INSERT INTO public.exercise_list (name, id) VALUES ('Face Pull', 137);
INSERT INTO public.exercise_list (name, id) VALUES ('Running', 138);
INSERT INTO public.exercise_list (name, id) VALUES ('Lunge (Dumbbell)', 139);
INSERT INTO public.exercise_list (name, id) VALUES ('Overhead Press (Smith Machine)', 140);
INSERT INTO public.exercise_list (name, id) VALUES ('Shrug (Machine)', 141);
INSERT INTO public.exercise_list (name, id) VALUES ('Skullcrusher (Dumbbell)', 142);
INSERT INTO public.exercise_list (name, id) VALUES ('Triceps Kickback (Dumbbell)', 143);
INSERT INTO public.exercise_list (name, id) VALUES ('Overhead Press (Dumbbell)', 144);
INSERT INTO public.exercise_list (name, id) VALUES ('Sled Push', 145);
