INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 120, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (95, 120, 'Lat Pulldown - Close Grip (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 120, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (66, 120, 'Incline Bench Press (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (49, 120, 'Iso-Lateral Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (62, 120, 'Seated Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (23, 120, 'Pullover (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 121, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (101, 121, 'Bayesian Cable Curl');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (110, 121, 'Hammer Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 121, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 121, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (44, 121, 'Rear Delt Reverse Fly (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (30, 121, 'Lateral Raise (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 122, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (49, 122, 'Iso-Lateral Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 122, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 122, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 122, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 123, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 123, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (77, 123, 'Iso-Lateral Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 123, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (87, 123, 'Reverse Curl (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (110, 123, 'Hammer Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 124, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (60, 124, 'Seated Cable Row - Bar Wide Grip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 124, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (62, 124, 'Seated Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 124, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 124, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (93, 125, 'Hack Squat (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (36, 125, 'Romanian Deadlift (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (21, 125, 'Seated Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 126, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (39, 126, 'Supine Press');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 126, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (87, 126, 'Reverse Curl (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 126, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 126, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (111, 126, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (21, 127, 'Seated Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (93, 127, 'Hack Squat (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (36, 127, 'Romanian Deadlift (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (83, 127, 'Bulgarian Split Squat');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (27, 127, 'Leg Raise Parallel Bars');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 128, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (62, 128, 'Seated Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (60, 128, 'Seated Cable Row - Bar Wide Grip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 128, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 128, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 128, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 129, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (77, 129, 'Iso-Lateral Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 129, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 129, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 129, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (67, 129, 'Preacher Curl (Hammer)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (30, 129, 'Lateral Raise (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 130, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (49, 130, 'Iso-Lateral Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (60, 130, 'Seated Cable Row - Bar Wide Grip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 130, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 130, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (21, 131, 'Seated Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (50, 131, 'Squat (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (36, 131, 'Romanian Deadlift (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (83, 131, 'Bulgarian Split Squat');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 132, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (66, 132, 'Incline Bench Press (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (42, 132, 'Cable Fly Crossovers');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 132, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 132, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (110, 132, 'Hammer Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (76, 132, 'Lateral Raise (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 133, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (47, 133, 'Chest Supported Incline Row (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (102, 133, 'Dumbbell Row');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (62, 133, 'Seated Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 133, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 133, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 133, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (21, 134, 'Seated Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (50, 134, 'Squat (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (36, 134, 'Romanian Deadlift (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (105, 134, 'Leg Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 135, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (77, 135, 'Iso-Lateral Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 135, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (89, 135, 'EZ Bar Biceps Curl');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (101, 135, 'Bayesian Cable Curl');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (29, 135, 'Hammer Curl Bar');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (111, 135, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (30, 135, 'Lateral Raise (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (5, 136, 'Pull Up');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (56, 136, 'Pull Up (Weighted)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (49, 136, 'Iso-Lateral Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (103, 136, 'T Bar Row');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (108, 136, 'Bent Over Row (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (44, 136, 'Rear Delt Reverse Fly (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 136, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 136, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 137, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (78, 137, 'Overhead Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 137, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 137, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 137, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (67, 137, 'Preacher Curl (Hammer)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 137, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (111, 137, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 138, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (77, 138, 'Iso-Lateral Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 138, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 138, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (87, 138, 'Reverse Curl (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 138, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (30, 138, 'Lateral Raise (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (34, 138, 'Preacher Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 139, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (51, 139, 'Meadows Rows (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (49, 139, 'Iso-Lateral Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (62, 139, 'Seated Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (60, 139, 'Seated Cable Row - Bar Wide Grip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 139, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (50, 140, 'Squat (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (21, 140, 'Seated Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 141, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (77, 141, 'Iso-Lateral Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (42, 141, 'Cable Fly Crossovers');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 141, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (34, 141, 'Preacher Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (101, 141, 'Bayesian Cable Curl');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (30, 141, 'Lateral Raise (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 142, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (49, 142, 'Iso-Lateral Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (62, 142, 'Seated Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (60, 142, 'Seated Cable Row - Bar Wide Grip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 142, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 142, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (85, 142, 'Seated Dip Machine');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (21, 143, 'Seated Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (74, 143, 'Seated Calf Raise');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (93, 143, 'Hack Squat (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (59, 143, 'Lying Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (105, 143, 'Leg Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 144, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (66, 144, 'Incline Bench Press (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (92, 144, 'Chest Fly (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 144, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (87, 144, 'Reverse Curl (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (101, 144, 'Bayesian Cable Curl');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (111, 144, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 145, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (49, 145, 'Iso-Lateral Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (60, 145, 'Seated Cable Row - Bar Wide Grip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 145, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 145, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 145, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (21, 146, 'Seated Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (93, 146, 'Hack Squat (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (24, 146, 'Deadlift (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (105, 146, 'Leg Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 147, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (77, 147, 'Iso-Lateral Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 147, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (87, 147, 'Reverse Curl (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 147, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 147, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (30, 147, 'Lateral Raise (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 148, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (62, 148, 'Seated Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (60, 148, 'Seated Cable Row - Bar Wide Grip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 148, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 148, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 148, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 149, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (39, 149, 'Supine Press');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 149, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 149, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (87, 149, 'Reverse Curl (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 149, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (111, 149, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 150, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (38, 150, 'Iso Lateral Low Row');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (53, 150, 'Seated Cable Row - V Grip (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (86, 150, 'Unilateral Rear Delts (Nipples)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 150, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 150, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 150, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (21, 151, 'Seated Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (93, 151, 'Hack Squat (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (24, 151, 'Deadlift (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (83, 151, 'Bulgarian Split Squat');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (80, 151, 'Hip Abduction (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (65, 151, 'Hip Adduction (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (98, 151, 'Crunch (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 152, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (39, 152, 'Supine Press');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 152, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 152, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 152, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (111, 152, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (27, 152, 'Leg Raise Parallel Bars');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 153, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (71, 153, 'Pull Up (Assisted)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (38, 153, 'Iso Lateral Low Row');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 153, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (31, 153, 'Triceps Kickback (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (27, 153, 'Leg Raise Parallel Bars');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 154, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (39, 154, 'Supine Press');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 154, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 154, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (111, 154, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 154, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (27, 154, 'Leg Raise Parallel Bars');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (21, 155, 'Seated Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (50, 155, 'Squat (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (105, 155, 'Leg Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (27, 155, 'Leg Raise Parallel Bars');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (49, 156, 'Iso-Lateral Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 156, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (46, 156, 'Shrug (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (60, 156, 'Seated Cable Row - Bar Wide Grip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 156, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 156, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 157, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (39, 157, 'Supine Press');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 157, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (87, 157, 'Reverse Curl (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (101, 157, 'Bayesian Cable Curl');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 157, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (111, 157, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (36, 158, 'Romanian Deadlift (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (58, 158, 'Shoulder Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (62, 158, 'Seated Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 158, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 159, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (49, 159, 'Iso-Lateral Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (60, 159, 'Seated Cable Row - Bar Wide Grip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 159, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 159, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 159, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 160, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (104, 160, 'Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 160, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (87, 160, 'Reverse Curl (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 160, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (111, 160, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (62, 161, 'Seated Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (49, 161, 'Iso-Lateral Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 161, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (60, 161, 'Seated Cable Row - Bar Wide Grip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (46, 161, 'Shrug (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 161, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (31, 161, 'Triceps Kickback (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (21, 162, 'Seated Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (50, 162, 'Squat (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (24, 162, 'Deadlift (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (105, 162, 'Leg Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (27, 162, 'Leg Raise Parallel Bars');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (66, 163, 'Incline Bench Press (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (77, 163, 'Iso-Lateral Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 163, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (34, 163, 'Preacher Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 163, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 164, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (108, 164, 'Bent Over Row (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (58, 164, 'Shoulder Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 164, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (31, 164, 'Triceps Kickback (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 165, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 165, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 165, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (111, 165, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (88, 165, 'Bicep Curl (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 165, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (110, 165, 'Hammer Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 166, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (26, 166, 'Iso-Lateral Low Row');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (108, 166, 'Bent Over Row (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (46, 166, 'Shrug (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 166, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 166, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (31, 166, 'Triceps Kickback (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (70, 167, 'Triceps Dip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 167, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (66, 167, 'Incline Bench Press (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (52, 167, 'Low Cable Fly Crossovers');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (42, 167, 'Cable Fly Crossovers');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (111, 167, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (27, 167, 'Leg Raise Parallel Bars');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 168, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (61, 168, 'Bench Press (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 168, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (34, 168, 'Preacher Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (75, 169, 'Squat (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (37, 169, 'Deadlift (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (106, 169, 'Leg Press Horizontal (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 170, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (108, 170, 'Bent Over Row (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (86, 170, 'Unilateral Rear Delts (Nipples)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (58, 170, 'Shoulder Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 170, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 170, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (31, 170, 'Triceps Kickback (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 171, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 171, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 171, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 171, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 171, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (111, 171, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (106, 171, 'Leg Press Horizontal (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 172, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (60, 172, 'Seated Cable Row - Bar Wide Grip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (53, 172, 'Seated Cable Row - V Grip (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (91, 172, 'Standing Calf Raise (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (86, 172, 'Unilateral Rear Delts (Nipples)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 172, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (31, 172, 'Triceps Kickback (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (66, 173, 'Incline Bench Press (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (104, 173, 'Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 173, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 173, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 173, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 174, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (53, 174, 'Seated Cable Row - V Grip (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (86, 174, 'Unilateral Rear Delts (Nipples)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (58, 174, 'Shoulder Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (46, 174, 'Shrug (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 174, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 174, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (31, 174, 'Triceps Kickback (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 175, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 175, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 175, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 175, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 175, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (76, 175, 'Lateral Raise (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (111, 175, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (59, 176, 'Lying Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (93, 176, 'Hack Squat (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (32, 176, 'Leg Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (83, 176, 'Bulgarian Split Squat');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (105, 176, 'Leg Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (80, 176, 'Hip Abduction (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (65, 176, 'Hip Adduction (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (98, 176, 'Crunch (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (5, 177, 'Pull Up');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 177, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (53, 177, 'Seated Cable Row - V Grip (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 177, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (46, 177, 'Shrug (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 177, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 177, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (31, 177, 'Triceps Kickback (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (66, 178, 'Incline Bench Press (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (104, 178, 'Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 178, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 178, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 178, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (50, 179, 'Squat (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (73, 179, 'Hip Thrust (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (59, 179, 'Lying Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (105, 179, 'Leg Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (91, 179, 'Standing Calf Raise (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (98, 179, 'Crunch (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (5, 180, 'Pull Up');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 180, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (53, 180, 'Seated Cable Row - V Grip (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 180, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (46, 180, 'Shrug (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 180, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 180, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (82, 180, 'Bench Dip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (76, 180, 'Lateral Raise (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (66, 181, 'Incline Bench Press (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (104, 181, 'Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 181, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 181, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (5, 182, 'Pull Up');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 182, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (53, 182, 'Seated Cable Row - V Grip (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 182, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (46, 182, 'Shrug (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 182, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 182, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (82, 182, 'Bench Dip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 183, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 183, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (101, 183, 'Bayesian Cable Curl');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 183, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 183, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 183, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (76, 183, 'Lateral Raise (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (66, 184, 'Incline Bench Press (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (104, 184, 'Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 184, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 184, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 184, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (66, 185, 'Incline Bench Press (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 185, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (104, 185, 'Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (101, 185, 'Bayesian Cable Curl');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 185, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 185, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 185, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (76, 185, 'Lateral Raise (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (5, 186, 'Pull Up');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 186, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (108, 186, 'Bent Over Row (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 186, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (46, 186, 'Shrug (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 186, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 186, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (82, 186, 'Bench Dip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 187, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 187, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 187, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (101, 187, 'Bayesian Cable Curl');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 187, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 187, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (5, 188, 'Pull Up');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (62, 188, 'Seated Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (26, 188, 'Iso-Lateral Low Row');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 188, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 188, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (46, 188, 'Shrug (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 188, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 188, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (82, 188, 'Bench Dip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (66, 189, 'Incline Bench Press (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (104, 189, 'Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (42, 189, 'Cable Fly Crossovers');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 189, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 189, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 189, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (76, 189, 'Lateral Raise (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 189, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (5, 190, 'Pull Up');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (71, 190, 'Pull Up (Assisted)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 190, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (103, 190, 'T Bar Row');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (46, 190, 'Shrug (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 190, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (82, 190, 'Bench Dip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (66, 191, 'Incline Bench Press (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (104, 191, 'Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (92, 191, 'Chest Fly (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (42, 191, 'Cable Fly Crossovers');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (101, 191, 'Bayesian Cable Curl');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 191, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 191, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (111, 191, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (5, 192, 'Pull Up');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (71, 192, 'Pull Up (Assisted)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (53, 192, 'Seated Cable Row - V Grip (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 192, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (46, 192, 'Shrug (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 192, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 192, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (82, 192, 'Bench Dip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (66, 193, 'Incline Bench Press (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (104, 193, 'Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (42, 193, 'Cable Fly Crossovers');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (101, 193, 'Bayesian Cable Curl');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 193, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 193, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (76, 193, 'Lateral Raise (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (111, 193, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (108, 194, 'Bent Over Row (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (97, 194, 'Iso-Lateral High Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (53, 194, 'Seated Cable Row - V Grip (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (46, 194, 'Shrug (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 194, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 195, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 195, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (81, 195, 'Seated Chest Flys (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 195, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (101, 195, 'Bayesian Cable Curl');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 195, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 195, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (76, 195, 'Lateral Raise (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (5, 196, 'Pull Up');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (71, 196, 'Pull Up (Assisted)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (62, 196, 'Seated Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 196, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (109, 196, 'Shrug (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 196, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 196, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (82, 196, 'Bench Dip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 197, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 197, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 197, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 197, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 197, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 197, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (111, 197, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (76, 197, 'Lateral Raise (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (50, 198, 'Squat (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (73, 198, 'Hip Thrust (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (59, 198, 'Lying Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (64, 198, 'Back Extension (Weighted Hyperextension)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (105, 198, 'Leg Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (91, 198, 'Standing Calf Raise (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (5, 199, 'Pull Up');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (71, 199, 'Pull Up (Assisted)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (62, 199, 'Seated Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 199, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (109, 199, 'Shrug (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (96, 199, 'Shrug (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 199, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 199, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (82, 199, 'Bench Dip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 200, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 200, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 200, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 200, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 200, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 200, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (30, 200, 'Lateral Raise (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (35, 201, 'Squat (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (32, 201, 'Leg Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (73, 201, 'Hip Thrust (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (59, 201, 'Lying Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (105, 201, 'Leg Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (80, 201, 'Hip Abduction (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (91, 201, 'Standing Calf Raise (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (5, 202, 'Pull Up');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (25, 202, 'Cross Arm Lat Pull Around');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (62, 202, 'Seated Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (53, 202, 'Seated Cable Row - V Grip (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 202, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (109, 202, 'Shrug (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 202, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 202, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (82, 202, 'Bench Dip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 203, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 203, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 203, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 203, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 203, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 203, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (76, 203, 'Lateral Raise (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (50, 204, 'Squat (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (105, 204, 'Leg Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (21, 204, 'Seated Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (73, 204, 'Hip Thrust (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (80, 204, 'Hip Abduction (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (45, 204, 'Calf Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (5, 205, 'Pull Up');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (71, 205, 'Pull Up (Assisted)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (62, 205, 'Seated Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (53, 205, 'Seated Cable Row - V Grip (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (96, 205, 'Shrug (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 205, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 205, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (82, 205, 'Bench Dip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (111, 205, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 206, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 206, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (81, 206, 'Seated Chest Flys (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 206, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (75, 207, 'Squat (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (21, 207, 'Seated Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (45, 207, 'Calf Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (105, 207, 'Leg Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (108, 208, 'Bent Over Row (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (53, 208, 'Seated Cable Row - V Grip (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (57, 208, 'Straight Arm Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (109, 208, 'Shrug (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 208, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 208, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (30, 208, 'Lateral Raise (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (85, 208, 'Seated Dip Machine');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (82, 208, 'Bench Dip');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 209, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 209, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 209, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (50, 210, 'Squat (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (73, 210, 'Hip Thrust (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (21, 210, 'Seated Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (105, 210, 'Leg Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (80, 210, 'Hip Abduction (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (112, 210, 'Decline Crunch');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (45, 210, 'Calf Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (5, 211, 'Pull Up');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (49, 211, 'Iso-Lateral Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (69, 211, 'Single Arm Lat Pulldown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (109, 211, 'Shrug (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 211, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 211, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 211, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (64, 211, 'Back Extension (Weighted Hyperextension)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (77, 212, 'Iso-Lateral Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 212, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 212, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 212, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 212, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 212, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 212, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (76, 212, 'Lateral Raise (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (108, 213, 'Bent Over Row (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (53, 213, 'Seated Cable Row - V Grip (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (5, 213, 'Pull Up');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (71, 213, 'Pull Up (Assisted)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (85, 213, 'Seated Dip Machine');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (109, 213, 'Shrug (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 213, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 213, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (66, 214, 'Incline Bench Press (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (68, 214, 'Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 214, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 214, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 214, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (100, 214, 'Spider Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (76, 214, 'Lateral Raise (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 215, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 215, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 215, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 215, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 215, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 215, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (111, 215, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (50, 216, 'Squat (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (73, 216, 'Hip Thrust (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (21, 216, 'Seated Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (105, 216, 'Leg Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (80, 216, 'Hip Abduction (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (5, 217, 'Pull Up');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (71, 217, 'Pull Up (Assisted)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (62, 217, 'Seated Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (109, 217, 'Shrug (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (43, 217, 'Single Arm Triceps Pushdown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 217, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 218, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 218, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (66, 218, 'Incline Bench Press (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 218, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 218, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 218, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 218, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (76, 218, 'Lateral Raise (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (50, 219, 'Squat (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (73, 219, 'Hip Thrust (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (21, 219, 'Seated Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (105, 219, 'Leg Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (80, 219, 'Hip Abduction (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (112, 219, 'Decline Crunch');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (45, 219, 'Calf Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (108, 220, 'Bent Over Row (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 220, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (53, 220, 'Seated Cable Row - V Grip (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (109, 220, 'Shrug (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 220, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (28, 220, 'Triceps Rope Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 220, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 220, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (33, 220, 'Seated Palms Up Wrist Curl');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 221, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 221, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 221, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 221, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 221, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 221, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (76, 221, 'Lateral Raise (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (50, 222, 'Squat (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (59, 222, 'Lying Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (21, 222, 'Seated Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (105, 222, 'Leg Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (112, 222, 'Decline Crunch');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (108, 223, 'Bent Over Row (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (53, 223, 'Seated Cable Row - V Grip (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (69, 223, 'Single Arm Lat Pulldown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (109, 223, 'Shrug (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 223, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 223, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (48, 223, 'Skullcrusher (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 223, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (77, 224, 'Iso-Lateral Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (66, 224, 'Incline Bench Press (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 224, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 224, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 224, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 224, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (30, 224, 'Lateral Raise (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (49, 225, 'Iso-Lateral Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (53, 225, 'Seated Cable Row - V Grip (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 225, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 225, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (109, 225, 'Shrug (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 225, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 225, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (32, 226, 'Leg Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (21, 226, 'Seated Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (73, 226, 'Hip Thrust (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (45, 226, 'Calf Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (77, 227, 'Iso-Lateral Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (66, 227, 'Incline Bench Press (Smith Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 227, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 227, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 227, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 227, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (111, 227, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (76, 227, 'Lateral Raise (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (108, 228, 'Bent Over Row (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (53, 228, 'Seated Cable Row - V Grip (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (69, 228, 'Single Arm Lat Pulldown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (109, 228, 'Shrug (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 228, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 228, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 228, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 229, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 229, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 229, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 229, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (107, 229, 'Incline Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 229, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (30, 229, 'Lateral Raise (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 230, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 230, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (76, 230, 'Lateral Raise (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (77, 230, 'Iso-Lateral Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (107, 230, 'Incline Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 230, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 230, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (111, 230, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (109, 231, 'Shrug (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 231, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 231, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (5, 231, 'Pull Up');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (71, 231, 'Pull Up (Assisted)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (49, 231, 'Iso-Lateral Row (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 231, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (108, 232, 'Bent Over Row (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (53, 232, 'Seated Cable Row - V Grip (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (109, 232, 'Shrug (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 232, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (72, 232, 'Lat Pulldown (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (85, 232, 'Seated Dip Machine');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (79, 232, 'Triceps Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (94, 232, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (50, 233, 'Squat (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (21, 233, 'Seated Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (105, 233, 'Leg Extension (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (112, 233, 'Decline Crunch');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (59, 233, 'Lying Leg Curl (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (108, 234, 'Bent Over Row (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (53, 234, 'Seated Cable Row - V Grip (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (69, 234, 'Single Arm Lat Pulldown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (109, 234, 'Shrug (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (84, 234, 'Triceps Pushdown');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (55, 234, 'Triceps Extension (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (63, 235, 'Butterfly (Pec Deck)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (104, 235, 'Chest Press (Machine)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (107, 235, 'Incline Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (41, 235, 'Preacher Curl (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 235, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (22, 235, 'Hammer Curl (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (76, 235, 'Lateral Raise (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (40, 236, 'Bench Press (Barbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (99, 236, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (81, 236, 'Seated Chest Flys (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (90, 236, 'Bicep Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (54, 236, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (22, 236, 'Hammer Curl (Cable)');
INSERT INTO public.exercise (machine_id, session_id, exercise_name) VALUES (76, 236, 'Lateral Raise (Dumbbell)');
