INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (6, 1, 1, null, 'Chest Press');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (8, 1, 2, null, 'Hip Abduction');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (10, 1, 3, null, 'Iso-lateral Row');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (4, 1, 4, null, 'Cable Bicep Curl');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (14, 1, 5, null, 'Pull Up');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (2, 1, 6, null, 'Bench Press');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (12, 1, 7, null, 'Leg Extension');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (9, 1, 9, null, 'Hip Adduction');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (7, 1, 10, null, 'Glute kickback');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (5, 1, 11, null, 'Calf Press');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (11, 1, 12, null, 'Lat Pulldown');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (1, 1, 13, null, 'Back Extension');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (15, 1, 14, null, 'Rowing Machine');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (13, 1, 15, null, 'Leg Press');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (3, 1, 16, null, 'Butterfly');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (19, 1, 17, null, 'Squat');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (17, 1, 18, null, 'Seated Row');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (16, 1, 19, null, 'Seated Leg Curl');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (18, 1, 20, null, 'Shrug');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (43, 1, 21, null, 'Seated Leg Curl (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (112, 1, 22, null, 'Hammer Curl (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (27, 1, 23, null, 'Pullover (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (68, 1, 24, null, 'Deadlift (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (99, 1, 25, null, 'Cross Arm Lat Pull Around');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (82, 1, 26, null, 'Iso-Lateral Low Row');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (48, 1, 27, null, 'Leg Raise Parallel Bars');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (107, 1, 28, null, 'Triceps Rope Pushdown');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (57, 1, 29, null, 'Hammer Curl Bar');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (34, 1, 30, null, 'Lateral Raise (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (77, 1, 31, null, 'Triceps Kickback (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (90, 1, 32, null, 'Leg Press (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (108, 1, 33, null, 'Seated Palms Up Wrist Curl');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (62, 1, 34, null, 'Preacher Curl (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (98, 1, 35, null, 'Squat (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (42, 1, 36, null, 'Romanian Deadlift (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (87, 1, 37, null, 'Deadlift (Smith Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (70, 1, 38, null, 'Iso Lateral Low Row');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (44, 1, 39, null, 'Supine Press');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (21, 1, 40, null, 'Bench Press (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (69, 1, 41, null, 'Preacher Curl (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (51, 1, 42, null, 'Cable Fly Crossovers');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (106, 1, 43, null, 'Single Arm Triceps Pushdown (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (33, 1, 44, null, 'Rear Delt Reverse Fly (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (100, 1, 45, null, 'Calf Extension (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (78, 1, 46, null, 'Shrug (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (53, 1, 47, null, 'Chest Supported Incline Row (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (109, 1, 48, null, 'Skullcrusher (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (25, 1, 49, null, 'Iso-Lateral Row (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (50, 1, 50, null, 'Squat (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (63, 1, 51, null, 'Meadows Rows (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (84, 1, 52, null, 'Low Cable Fly Crossovers');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (71, 1, 53, null, 'Seated Cable Row - V Grip (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (45, 1, 54, null, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (32, 1, 55, null, 'Triceps Extension (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (58, 1, 56, null, 'Pull Up (Weighted)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (101, 1, 57, null, 'Straight Arm Lat Pulldown (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (79, 1, 58, null, 'Shoulder Press (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (66, 1, 59, null, 'Lying Leg Curl (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (40, 1, 60, null, 'Seated Cable Row - Bar Wide Grip');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (85, 1, 61, null, 'Bench Press (Smith Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (26, 1, 62, null, 'Seated Row (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (37, 1, 63, null, 'Butterfly (Pec Deck)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (96, 1, 64, null, 'Back Extension (Weighted Hyperextension)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (74, 1, 65, null, 'Hip Adduction (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (24, 1, 66, null, 'Incline Bench Press (Smith Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (49, 1, 67, null, 'Preacher Curl (Hammer)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (104, 1, 68, null, 'Bench Press (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (103, 1, 69, null, 'Single Arm Lat Pulldown');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (83, 1, 70, null, 'Triceps Dip');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (76, 1, 71, null, 'Pull Up (Assisted)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (35, 1, 72, null, 'Lat Pulldown (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (91, 1, 73, null, 'Hip Thrust (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (65, 1, 74, null, 'Seated Calf Raise');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (86, 1, 75, null, 'Squat (Smith Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (52, 1, 76, null, 'Lateral Raise (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (38, 1, 77, null, 'Iso-Lateral Chest Press (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (61, 1, 78, null, 'Overhead Press (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (111, 1, 79, null, 'Triceps Extension (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (73, 1, 80, null, 'Hip Abduction (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (94, 1, 81, null, 'Seated Chest Flys (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (92, 1, 82, null, 'Bench Dip');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (47, 1, 83, null, 'Bulgarian Split Squat');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (31, 1, 84, null, 'Triceps Pushdown');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (64, 1, 85, null, 'Seated Dip Machine');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (72, 1, 86, null, 'Unilateral Rear Delts (Nipples)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (39, 1, 87, null, 'Reverse Curl (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (81, 1, 88, null, 'Bicep Curl (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (56, 1, 89, null, 'EZ Bar Biceps Curl');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (28, 1, 90, null, 'Bicep Curl (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (89, 1, 91, null, 'Standing Calf Raise (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (67, 1, 92, null, 'Chest Fly (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (41, 1, 93, null, 'Hack Squat (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (36, 1, 94, null, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (22, 1, 95, null, 'Lat Pulldown - Close Grip (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (97, 1, 96, null, 'Shrug (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (93, 1, 97, null, 'Iso-Lateral High Row (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (75, 1, 98, null, 'Crunch (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (23, 1, 99, null, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (105, 1, 100, null, 'Spider Curl (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (29, 1, 101, null, 'Bayesian Cable Curl');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (54, 1, 102, null, 'Dumbbell Row');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (59, 1, 103, null, 'T Bar Row');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (80, 1, 104, null, 'Chest Press (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (55, 1, 105, null, 'Leg Extension (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (88, 1, 106, null, 'Leg Press Horizontal (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (110, 1, 107, null, 'Incline Bench Press (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (60, 1, 108, null, 'Bent Over Row (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (95, 1, 109, null, 'Shrug (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (30, 1, 110, null, 'Hammer Curl (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (46, 1, 111, null, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (102, 1, 112, null, 'Decline Crunch');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (113, 1, 113, null, 'Single Arm Cable Row');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (114, 1, 114, null, 'Bicep Curl (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (115, 1, 115, null, 'Reverse Grip Smith machine Flat Bench Press');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (116, 1, 116, null, 'Chest Fly (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (117, 1, 117, null, 'Iso-Lateral Machine Row');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (118, 1, 118, null, 'Seated Cable Row - Bar Grip');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (119, 1, 119, null, 'Lying Chest Press');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (120, 1, 120, null, 'Back Extension (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (121, 1, 121, null, 'Incline Chest Press (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (122, 1, 122, null, 'Chin Up (Weighted)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (123, 1, 123, null, 'Triceps Dip (Weighted)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (124, 1, 124, null, 'Decline Push Up');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (125, 1, 125, null, 'Diamond Push Up');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (126, 1, 126, null, 'Handstand Hold');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (127, 1, 127, null, 'Ring Dips');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (128, 1, 128, null, 'Incline Push Ups');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (129, 1, 129, null, 'Drinks');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (130, 1, 130, null, 'Pullover (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (131, 1, 131, null, 'Belt Squat');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (132, 1, 132, null, 'Bicep Curl (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (133, 1, 133, null, 'Nordic Hamstrings Curls');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (134, 1, 134, null, 'Reverse Curl (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (135, 1, 135, null, 'Upright Row (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (136, 1, 136, null, 'Standing Leg Curls');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (137, 1, 137, null, 'Rear Delt Reverse Fly (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (138, 1, 138, null, 'Preacher Curl (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (139, 1, 139, null, 'Dead Hang');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (140, 1, 140, null, 'Farmers Walk');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (141, 1, 141, null, 'Seated Shoulder Press (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (142, 1, 142, null, 'Concentration Curl');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (143, 1, 143, null, 'Shrug (Smith Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (144, 1, 144, null, 'Cable Crunch');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (145, 1, 145, null, 'Seated Wrist Extension (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (146, 1, 146, null, 'Calf Press (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (147, 1, 147, null, 'Hanging Leg Raise');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (148, 1, 148, null, 'Lateral Raise (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (149, 1, 149, null, 'Lying Neck Curls (Weighted)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (150, 1, 150, null, 'Lying Neck Extension (Weighted)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (151, 1, 151, null, 'Face Pull');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (152, 1, 152, null, 'Running');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (153, 1, 153, null, 'Lunge (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (154, 1, 154, null, 'Overhead Press (Smith Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (155, 1, 155, null, 'Shrug (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (156, 1, 156, null, 'Skullcrusher (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (157, 1, 157, null, 'Triceps Kickback (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (158, 1, 158, null, 'Overhead Press (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, machine_id, last_time_checked, name) VALUES (159, 1, 159, null, 'Sled Push');
