INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (6, 1, null, 'Chest Press');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (8, 1, null, 'Hip Abduction');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (10, 1, null, 'Iso-lateral Row');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (4, 1, null, 'Cable Bicep Curl');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (14, 1, null, 'Pull Up');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (2, 1, null, 'Bench Press');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (12, 1, null, 'Leg Extension');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (20, 1, '2024-12-09 10:14:42.000000', 'Tricep Dip');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (9, 1, null, 'Hip Adduction');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (7, 1, null, 'Glute kickback');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (5, 1, null, 'Calf Press');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (11, 1, null, 'Lat Pulldown');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (1, 1, null, 'Back Extension');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (15, 1, null, 'Rowing Machine');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (13, 1, null, 'Leg Press');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (3, 1, null, 'Butterfly');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (19, 1, null, 'Squat');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (17, 1, null, 'Seated Row');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (16, 1, null, 'Seated Leg Curl');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (18, 1, null, 'Shrug');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (43, 1, null, 'Seated Leg Curl (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (112, 1, null, 'Hammer Curl (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (27, 1, null, 'Pullover (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (68, 1, null, 'Deadlift (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (99, 1, null, 'Cross Arm Lat Pull Around');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (82, 1, null, 'Iso-Lateral Low Row');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (48, 1, null, 'Leg Raise Parallel Bars');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (107, 1, null, 'Triceps Rope Pushdown');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (57, 1, null, 'Hammer Curl Bar');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (34, 1, null, 'Lateral Raise (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (77, 1, null, 'Triceps Kickback (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (90, 1, null, 'Leg Press (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (108, 1, null, 'Seated Palms Up Wrist Curl');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (62, 1, null, 'Preacher Curl (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (98, 1, null, 'Squat (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (42, 1, null, 'Romanian Deadlift (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (87, 1, null, 'Deadlift (Smith Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (70, 1, null, 'Iso Lateral Low Row');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (44, 1, null, 'Supine Press');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (21, 1, null, 'Bench Press (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (69, 1, null, 'Preacher Curl (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (51, 1, null, 'Cable Fly Crossovers');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (106, 1, null, 'Single Arm Triceps Pushdown (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (33, 1, null, 'Rear Delt Reverse Fly (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (100, 1, null, 'Calf Extension (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (78, 1, null, 'Shrug (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (53, 1, null, 'Chest Supported Incline Row (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (109, 1, null, 'Skullcrusher (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (25, 1, null, 'Iso-Lateral Row (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (50, 1, null, 'Squat (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (63, 1, null, 'Meadows Rows (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (84, 1, null, 'Low Cable Fly Crossovers');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (71, 1, null, 'Seated Cable Row - V Grip (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (45, 1, null, 'Seated Incline Curl (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (32, 1, null, 'Triceps Extension (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (58, 1, null, 'Pull Up (Weighted)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (101, 1, null, 'Straight Arm Lat Pulldown (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (79, 1, null, 'Shoulder Press (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (66, 1, null, 'Lying Leg Curl (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (40, 1, null, 'Seated Cable Row - Bar Wide Grip');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (85, 1, null, 'Bench Press (Smith Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (26, 1, null, 'Seated Row (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (37, 1, null, 'Butterfly (Pec Deck)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (96, 1, null, 'Back Extension (Weighted Hyperextension)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (74, 1, null, 'Hip Adduction (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (24, 1, null, 'Incline Bench Press (Smith Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (49, 1, null, 'Preacher Curl (Hammer)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (104, 1, null, 'Bench Press (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (103, 1, null, 'Single Arm Lat Pulldown');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (83, 1, null, 'Triceps Dip');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (76, 1, null, 'Pull Up (Assisted)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (35, 1, null, 'Lat Pulldown (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (91, 1, null, 'Hip Thrust (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (65, 1, null, 'Seated Calf Raise');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (86, 1, null, 'Squat (Smith Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (52, 1, null, 'Lateral Raise (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (38, 1, null, 'Iso-Lateral Chest Press (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (61, 1, null, 'Overhead Press (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (111, 1, null, 'Triceps Extension (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (73, 1, null, 'Hip Abduction (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (94, 1, null, 'Seated Chest Flys (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (92, 1, null, 'Bench Dip');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (47, 1, null, 'Bulgarian Split Squat');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (31, 1, null, 'Triceps Pushdown');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (64, 1, null, 'Seated Dip Machine');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (72, 1, null, 'Unilateral Rear Delts (Nipples)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (39, 1, null, 'Reverse Curl (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (81, 1, null, 'Bicep Curl (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (56, 1, null, 'EZ Bar Biceps Curl');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (28, 1, null, 'Bicep Curl (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (89, 1, null, 'Standing Calf Raise (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (67, 1, null, 'Chest Fly (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (41, 1, null, 'Hack Squat (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (36, 1, null, 'Rear Delt Reverse Fly (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (22, 1, null, 'Lat Pulldown - Close Grip (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (97, 1, null, 'Shrug (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (93, 1, null, 'Iso-Lateral High Row (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (75, 1, null, 'Crunch (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (23, 1, null, 'Incline Bench Press (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (105, 1, null, 'Spider Curl (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (29, 1, null, 'Bayesian Cable Curl');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (54, 1, null, 'Dumbbell Row');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (59, 1, null, 'T Bar Row');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (80, 1, null, 'Chest Press (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (55, 1, null, 'Leg Extension (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (88, 1, null, 'Leg Press Horizontal (Machine)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (110, 1, null, 'Incline Bench Press (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (60, 1, null, 'Bent Over Row (Barbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (95, 1, null, 'Shrug (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (30, 1, null, 'Hammer Curl (Dumbbell)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (46, 1, null, 'Single Arm Lateral Raise (Cable)');
INSERT INTO public.machine (arduino_id, gym_id, last_time_checked, name) VALUES (102, 1, null, 'Decline Crunch');
