INSERT INTO public.routine_exercise (routine_id, name) VALUES (8, 'Butterfly');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (8, 'Hip Abduction');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (8, 'Glute Kickback');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (8, 'Iso-lateral Row');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (9, 'Back Extension');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (9, 'Bench Press');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (10, 'Seated Dip Machine');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (10, 'Seated Dip Machine');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (10, 'Lying Leg Curl (Machine)');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (10, 'Seated Dip Machine');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (10, 'Seated Dip Machine');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (10, 'Seated Dip Machine');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (10, 'Lying Leg Curl (Machine)');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (10, 'Lying Leg Curl (Machine)');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (11, 'Iso-lateral Row');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (11, 'Deadlift (Barbell)');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (11, 'Seated Calf Raise');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (11, 'Preacher Curl (Barbell)');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (11, 'Deadlift (Barbell)');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (11, 'Seated Calf Raise');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (11, 'Preacher Curl (Barbell)');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (18, 'Glute Kickback');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (19, 'Iso-lateral Row');
INSERT INTO public.routine_exercise (routine_id, name) VALUES (19, 'Glute Kickback');
