INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (5, 4, 'Preacher Curl (Machine)');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (6, 4, 'Cable Bicep Curl');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (7, 4, 'Chest Fly (Dumbbell)');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (71, 20, 'Deadlift (Barbell)');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (72, 20, 'Chest Fly (Dumbbell)');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (73, 20, 'Deadlift (Barbell)');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (74, 21, 'Deadlift (Barbell)');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (75, 21, 'Chest Fly (Dumbbell)');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (76, 21, 'Deadlift (Barbell)');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (88, 26, 'Iso-lateral Row');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (89, 26, 'Preacher Curl (Barbell)');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (90, 26, 'Seated Calf Raise');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (91, 27, 'Iso-lateral Row');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (92, 28, 'Deadlift (Smith Machine)');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (93, 28, 'Bicep Curl (Dumbbell)');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (94, 29, 'Iso-lateral Row');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (95, 29, 'Deadlift (Smith Machine)');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (96, 30, 'Deadlift (Smith Machine)');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (61, 15, 'Lying Leg Curl (Machine)');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (62, 15, 'Lying Leg Curl (Machine)');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (128, 39, 'Iso-Lateral High Row (Machine)');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (129, 39, 'Iso-Lateral High Row (Machine)');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (130, 39, 'Glute Kickback');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (131, 39, 'Iso-Lateral High Row (Machine)');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (132, 39, 'Hip Thrust (Barbell)');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (133, 39, 'Back Extension');
INSERT INTO public.routine_exercise (exercise_id, routine_id, name) VALUES (134, 39, 'Iso-lateral Row');
